ossf/wg-best-practices-os-developers

README.md
We have some best practices work not linked, or the links aren't good ones.
Let's fix that.
Also: Everything is continuing in some sense, so I instead added "(incubating)" to show drafts not ready to use.
=> README.md - ensure all work has a link

docs/Existing Guidelines for Developing and Distributing Secure Software.md
Remove duplicated entries for Python and Kubernetes.
=> guidelines: remove duplications

README.md
=> Add links to one-pagers

docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
This PR adds the "Concise Guide for Evaluating Open Source Software" document to the repository.
=> Add Concise Guide for Evaluating Open Source Software

docs/Concise-Guide-for-Developing-More-Secure-Software.md, docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
=> Note that tools/services listed are merely examples

docs/Concise-Guide-for-Developing-More-Secure-Software.md, docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
The Concise Guides have dates at the top - if we're going to do that,
they should be correct ;-).
=> Update Concise Guide's dates

README.md
=> Add links to Concise guides from README

docs/Concise-Guide-for-Developing-More-Secure-Software.md
=> Add "prefer memory-safe languages"

README.md
Update Marta's affiliation and GitHub account
Signed-off-by: Marta Rybczynska <rybczynska@gmail.com>
=> Update Marta's data

README.md
=> Fix markdown lint errors, fixes #110

README.md
We welcome contributions, so make sure this is clearly said in the README.
Signed-off-by: Marta Rybczynska <rybczynska@gmail.com>
=> README.md: add information on how to contribute

docs/Concise-Guide-for-Developing-More-Secure-Software.md, docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
We welcome suggestions and contributions to those guides and other document, so add a link to create an issue or a pull request.
Signed-off-by: Marta Rybczynska <rybczynska@gmail.com>
=> docs/concise-guide*: ask for suggestions/updates

README.md
=> Fixing a link in the Readme

docs/Concise-Guide-for-Developing-More-Secure-Software.md, docs/Vendored-Dependencies-Guide.md
=> Create Vendored Dependencies Guide

docs/SCM-BestPractices/README.md, docs/SCM-BestPractices/github/README.md, docs/SCM-BestPractices/gitlab/README.md
Made the following changes:
- A few edits to the intro section
- Added an audience section
- Moved organizational management section to operations
- Added GitLab items to the organization section
- Added an intro and operation sections to the GitHub and GitLab READMEs
- Small typo fixes
=> SCM Guide: Enhance introductory content

docs/_includes/custom-head.html
To make things easy, I'm just copying the favicon invocations from the main openssf.org site. I'm also just referencing the files, instead of copying them in.
=> Add favicons

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Add list of considered but excluded options

docs/Concise-Guide-for-Developing-More-Secure-Software.md, docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
This PR adds publication dates to 2 of the guides being published on best.openssf.org.
=> Add publication date

docs/SCM-BestPractices/README.md
Fix spelling of OpenSSF for documentation introduced in #180
=> fix openssf spelling

docs/SCM-BestPractices/README.md, docs/SCM-BestPractices/github/README.md, docs/SCM-BestPractices/gitlab/README.md
Bundled a few changes here based on previous feedback:
1.  There was an ask to add language in the operational section around what one should do when taking a repo public - basically run through the repository configuration checks. So added a one-liner for that as well as checks that should also take place when a repo is transferred into an org.
2. Based on (1) it made sense to change the title in one of the headers from "Repository configuration" to "Repository". This is mainly because some items on that list are not really about configuration - ex: keeping a repository up to date or Scorecard score above 7.
3. Lastly, there's been some confusion around employees and tried to use language to make this apply only to say companies.
=> Additional repository operational recommendations 

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Rebased approved commits form #185.
=> Update compiler guide contributors

docs/SCM-BestPractices/README.md, docs/SCM-BestPractices/github/README.md, docs/SCM-BestPractices/gitlab/README.md
Change based on a recent project discussion to order tools alphabetically for simplicity, even though there are some that may have more functionality.
=> Tools reordering to alphabetically

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This covers the 2nd half of the current draft.
=> Compiler Guide: a few more typo and minor fixes

docs/securesoftwaredevelopmentguidingprinciples-signatures.md
Hello! 
This PR is to add your name or organization as a Signature for the [Secure Software Development Guiding Principles version 1.0](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SecureSoftwareGuidingPrinciples.md)
If you endorse and commit to these ideals then please add your name to this PR as a comment.
In your comment include your full name and include a link to your GitHub/website plus any title for us to add to the [signatory page](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/securesoftwaredevelopmentguidingprinciples-signatures.md)
=> Signatories For Secure Software Development Guiding Principles version 1.0

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Add organization and date for initial release

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
I don't think we can easily argue that this particular configuration is the "best balance" in all cases. As Disconnect3d from Trail of Bits noted in Slack, "citation needed :-)". Trade-offs are *way* too complicated to baldly state something is always the "best balance".
So instead, just say it's a "good balance". There may be a better balance for your circumstance, but since this is a good balance, we can recommend it.
=> best -> good

docs/developers.md
Add recently-released guides, fix a typo
=> Update developer landing page

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
We talk *briefly* about this before the background, but I think it'd be useful to expand on it. This includes the terms "green field" and "brown field", to help those familiar with those terms.
=> Discuss further how to apply the guide

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Bump date for Compiler Options Hardening Guide for C and C++

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Move GCC-specific options to situational options table from tl;dr and add explicit note on feature-parity between compilers

README.md
This PR add @ran-dall as a Co-Lead for the Best Practices Working Group.
=> Add Randall as Co-Lead

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Move improved compiling compilers section to end of document

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This adds some `-Werror` flags to help people switch to Modern C instead of some problematic legacy constructs.
=> Add options to require use of Modern C (fixes #339)

README.md
just a quick PR to update my affiliation in the readme doc
=> Update my affiliation

docs/labs/input1.html
This is a test; I don't know if this will work well.
=> Have sample lab use default website style

docs/labs/checker.js, docs/labs/create_labs.md, docs/labs/csp1.html, docs/labs/input1.html, docs/labs/input2.html
Labs can have problems. Implement a mechanism to help debug labs, and document how to debug labs more generally.
=> Add debug information for labs

docs/labs/csp1.html, docs/labs/input1.html, docs/labs/input2.html
This implements feedback from the Education SIG (specifically CRob).
=> Bold the main sentence describing the lab task

docs/labs/csp1.html, docs/labs/input1.html, docs/labs/input2.html
Making the "task" text bold doesn't make it obvious enough. I left it bold, but moved the one-sentence task text up to the top as its own sections. We now have the following sections:
* Task - one-sentence description of the task to be done
* Background - background general information
* Task Information - specific information on how to perform the task
* Interactive Lab - the interactive exercise
=> Further emphasize the task to be done

docs/labs/checker.js, docs/labs/create_checker.md
Continued cleanup for clarity.
=> Clean up checker documentation and comments

docs/labs/README.md, docs/labs/hello.html
Add a *really* simple lab, so people can get used to the buttons and so on without trying to also figure out something from the class.
=> Add a demo lab "hello.html"

docs/labs/checker.js
Detect and report on more input problems:
* Modify checker so it reports any unexpected fields in `info` or each hint.
* Report on a hint that has no `absent` and no `present` and is not last; such a hint always succeeds and means the later hints cannot ever trigger. Doing this *last* is okay (that creates a default hint).
=> In lab framework checker.js, report various input problems

docs/labs/csp1.html, docs/labs/hello.html, docs/labs/input1.html, docs/labs/input2.html
Modify tags to improve the code section formatting.
=> Labs: Change <pre>..</pre> to <pre><code>..</code></pre>

docs/labs/checker.js, docs/labs/csp1.html, docs/labs/hello.html, docs/labs/input1.html, docs/labs/input2.html
Add stamp on completion. This is useful if the lab is being used in a class, to provide evidence if people simply copy the same file to show they did the work.
=> Add datetime/uuid stamp at bottom on completion

docs/labs/README.md
This commit makes the locations consistent with this proposal: https://github.com/ossf/secure-sw-dev-fundamentals/pull/151
=> Identify where existing labs are expected to go

docs/labs/README.md, docs/labs/regex0.html, docs/labs/regex1.html
Some learners may skip this, but let's give a simple introduction for those who have never seen regexes.
=> Add lab "regex0"

docs/labs/regex0.html
I made an error in regex0, this fixes it
=> Fix regex0

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This fixes an unintended line break.
=> Fixing an unintended line break in a table

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This PR adds `-Werror=format-security` to list of recommended options.
The option treats conditions that are likely to case [format string vulnerabilities](https://cs155.stanford.edu/papers/formatstring-1.2.pdf) as errors. It only affects format strings that are not string literals and _used without arguments_ and is therefor unlikely to cause problems in benign code making use of format strings via variables. 
Making `-Wformat-security` be an error by default in Clang has been [discussed before on the LLVM mailing list](https://lists.llvm.org/pipermail/cfe-dev/2016-February/047367.html) but ultimately left up to the distributions, [with the conclusion](https://lists.llvm.org/pipermail/cfe-dev/2016-February/047438.html) that 
> [...] it's totally reasonable for vendors to want to make …
=> Add -Werror=format-security to list of recommended options

docs/labs/oob1.html
There are many variations of possible answers for oob1. Be more generous by allowing more of them.
This uses the new "definitions" capability
(and is a demonstration of their use).
=> Expand the answers allowed by oob1

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Add extra details for clang-tidy
https://github.com/ossf/wg-best-practices-os-developers/pull/438#discussion_r1559372249
=> Extend clang-tidy notes related to trojan source lints

docs/labs/README.md
=> Labs: Commit to handling errors

docs/labs/handling-errors.html
Adding Lab for Handling Errors section
=> Labs: Handling Errors Lab

docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/README.md, docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/compliant01.py, docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/compliant02.py, docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/compliant03.py, docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/noncompliant01.py, docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/noncompliant02.py, docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/noncompliant03.py, docs/Secure-Coding-Guide-for-Python/readme.md
As part of #531 converting confluence to MD
=> pyCode2GitHub_CWE-1095

docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/README.md, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/compliant01.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/compliant02.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/compliant03.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/noncompliant01.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/noncompliant02.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/noncompliant03.py, docs/Secure-Coding-Guide-for-Python/readme.md
Adding code and doc for CWE-191 as part of #531 .
=> pyDoc2GitHub CWE-191

docs/labs/README.md
This records our new volunteers for creating labs (thank you!!).
=> J Howard and others have volunteered to work on some labs

docs/labs/README.md
Added missing work "help" re: the call to help create labs (typo fix)
=> Add missing word in README.md

docs/labs/README.md, docs/labs/introduction.md
The labs introduction had gotten out of date - update it.
=> Update introduction to labs

docs/labs/regex1.html
Various minor fixes:
* Fix heading ends to match their beginnings
* Add link to OpenSSF guide "Correctly Using Regular Expressions for Secure Input Validation" <https://best.openssf.org/Correctly-Using-Regular-Expressions>
* Add hint if user incorrectly adds unnecessary quote marks.
=> Fix regex1

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Add -Wl,--as-needed and -Wl, --no-copy-dt-needed-entries to C and C++ Compiler Hardening Guide

docs/labs/shell-injection.html
Some learners will be familiar with Python, but others won't. Modify the lab text and the hints to help learners less familiar with Python.
=> Modify shell-injection to make it easier for learners

docs/labs/checker.js
Warn if there is a button not in a form, and
add an alert if there's an exception while looking for indexes.
=> Add warnings if labs have errors

docs/labs/shell-injection.html
Add more hints to the lab shell-injection.html.
This will help learners better understand what they need to do.
=> shell-injection.html: Add more hints

docs/labs/sql-injection.html
These were fixes proposed per review.
=> sql-injection.html: add various fixes

docs/labs/README.md
=> README.md - lab sql-injection.html done

docs/labs/README.md, docs/labs/sql-injection.html
Fix various problems in the SQL lab. Its example now matches the material in the course, and has more hints.
=> sql-injection.html: Various fixups

docs/labs/sql-injection.html
We never mentioned the programming language.
Specifically mention that it's Java, that's important information :-).
=> sql-injection.html: Clarify that this is Java

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Added recent contributors from GitHub and the C/C++ Compiler BP Calls.
It's entirely possible I've missed someone, so please add to this PR if you realize someone is missing.
As with #185 and #291 I will reach out to these individuals to confirm they consent to be named in the guide before merging.
=> Update compiler guide contributors 

docs/labs/README.md
=> We have a volunteer for Insecure Deserialization!

docs/labs/shell-injection.html
This hint was inspired by sipaynehsl
who mentioned adding unnecessary parentheses. See: https://forum.linuxfoundation.org/discussion/866580/how-do-i-run-the-lab-exercises
=> shell-injection: Give hint about unnecessary parentheses

docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-681/README.md, docs/Secure-Coding-Guide-for-Python/readme.md
Adding documentation to CWE-681 as part of #531
=> Adding documentation to CWE-681 as part of #531

docs/labs/shell-argument-injection.html
Hi @david-a-wheeler 👋
Got to stumble upon the OpenSSF Secure Coding Labs a couple of months back and really like the idea. Congrats on creating and launching this to you and all the team involved.
If you'd be interested in further expanding on some of the labs exercises I'm happy to contribute another lesson and lab on Argument Injection (a sub-class of command injection security issues).
This is an initial write-up for the lesson with the contents and if you'd want to welcome this in I'd gladly continue to add up the interactive bits for the HTML scripts that require the expected code and the hints/solution.
=> feat: add new argument injection lab

docs/Correctly-Using-Regular-Expressions-Rationale.md
This adds a simple invitation to open issues to the bottom of the  Regexp "Rationale" document.
=> Add invitation to open issues

README.md
Extremely minor: there was an extra '>' to close the image tag, so I removed it.
=> remove extra closing tag for the image

docs/labs/checker.js
Internationalize lab code. Use the HTML lang=... attribute to determine the locale (language) of the lab. This supports:
* Built0-in text - includes a Japanese translation
* Lab-specific text - you can use "text_LOCALE" which is preferred for the given LOCAE, otherwise use "text".
=> Internationalize lab

docs/translations.md
Use a bullet list so the list of names doesn't blend together.
=> translations.md: Minor formatting fix

docs/Compiler-Hardening-Guides/Compiler-Annotations-for-C-and-C++.md
Mark Compiler Annotations Guide as draft document
=> Mark Compiler Annotations Guide as draft document

README.md
I redid the formatting of the presentation as a new deck. This pull request updates the link to point to this new version.
=> Update link to brief introduction slides

docs/Secure-Coding-Guide-for-Python/readme.md
adding 778 to main python secure coding readme
=> pySCG: adding 778 to main readme.md

docs/labs/csp1.js, docs/labs/ja_csp1.html
This PR adds Japanese translation for docs/labs/csp1.html
As usual, please review the translation first @ninan27 @Muuhh-CTJ
=> ja_csp1.html: Add Japanese translation for labs/csp1

docs/labs/oob1.html
Possibly a typo but please ignore if it is not.
This is a prep of my Japanese translation.
=> Correct a typo in oob1.html

docs/index.md
This add the newly released Simplifying Software Component Updates guide to the published list of guides.
=> Listing the Simplifying Software Component Updates guide

docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-1335/README.md, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-1335/example01.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-1335/example02.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-1335/example03.py, docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-1335/noncompliant01.py, docs/Secure-Coding-Guide-for-Python/readme.md
As part of #531 adding 2nd 1335 doc and code
This time using html tag's for tables in Reference section to see if that works better.
=> pySCG: addign 2nd 1335 rule doc and code

docs/labs/ja_oob1.html, docs/labs/oob1.js
Japanese translation for docs/labs/oob1.html and oob1.js
I would like @ninan27 @shimos to review Japanese translation part first.
And, I appriciated if a mainter could label "Japanese" (and "Product: Labs").
=> Japanese translation of oob1

docs/labs/ja_regex0.html, docs/labs/regex0.js
Japanese translation for docs/labs/regex0.html and regex0.js
I would like @ninan27 @shimos to review Japanese translation part first.
=> Japanese translation of regex0

docs/labs/assert.js, docs/labs/ja_assert.html
Japanese translaton for docs/labs/assert.html and assert.js
I would like @ninan27 @shimos to review Japanese translation part first.
And I appriciated if a mainter could label "Japanese" on this PR.
=> Japanese translation of assert

docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
=> Fix other considerations heading level in `-ftrapv` description

docs/Security-Focused-Guide-for-AI-Code-Assistant-Instructions.md
Add notes in the AI guide about the organization different people come from.  We encourage many organizations to work together, and in this case that has clearly happened, so make that clear!
=> Add organization notes

docs/Compiler-Hardening-Guides/Compiler-Annotations-for-C-and-C++.md
This PR adds a detailed description of the `tainted_args` attribute to the Compiler Annotations Guide
=> Add detailed description of tainted_args to Compiler Annotations Guide

docs/Secure-Coding-Guide-for-Python/CWE-693/CWE-472/README.md, docs/Secure-Coding-Guide-for-Python/CWE-693/CWE-472/example01.py
Pull Request for the example01.py and the README.md for CWE-472
=> CWE-472: External Control of Assumed-Immutable Web Parameter

docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-366/README.md, docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-366/compliant01.py, docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-366/example01.py, docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-366/noncompliant01.py, docs/Secure-Coding-Guide-for-Python/Intro_to_multiprocessing_and_multithreading/readme.md, docs/Secure-Coding-Guide-for-Python/readme.md
The previous pull request got blocked on DCO.
There were some problems with fixing it, so I'm creating a new one.
=> CWE-366: Race Condition within a Thread
