ossf/wg-best-practices-os-developers

- docs/Existing Guidelines for Developing and Distributing Secure Software.md
Add some missing languages and the link to CWE from the call on
2022-03-01, and two resources for docker.
> guidelines: add missing languages

- docs/Concise-Guide-for-Developing-More-Secure-Software.md
- docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
The concise guides are already under version control, we don't need a date (that will itself go out of date).
> Remove dates from Concise Guides

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- docs/Compiler_Hardening_Guides/Toolchain-Hardening-for-C-and-C++.md
As discussed during the C/C++ Compiler Options BP Guide call on 2023-02-15 I'm opening this draft PR in order to share the initial Markdown draft of the "Toolchain Hardening for C and C++" guide from Ericsson. There were already good suggestions for improvement during the call. We can use this PR to continue the discussion and start incorporating changes.
> Add initial draft of Toolchain Hardening for C and C++ guide

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
It would be nice if readers could click on a compiler flag in a summary and immediately see the details about that flag.
I propose adding hyperlinks to implement that. It would make the markdown a *little* messier, but not outrageously so, and it would make the document *much* easier to navigate. I think we need to make it *easy* for readers to get from a summary to the details they need, or they won't read the details they need.
This adds an internal hyperlink from a flag description in a summary to an anchor on the details. The anchor is a span with id; I could have used a name="..." instead, but many seem to be preferring id so I used that. The id is exactly the flag name (e.g., `-fstack-protector-strong`); leading dashes *are* allowed in ids.
NB: The sample entry makes 1 table entry …
> Add sample hyperlink for -fstack-protector-strong

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This adds more links to allow for quickly jumping to the relevant section of the document by clicking on a compiler option in the overview table.
> Adding more links for quick navigability

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This adds some information from the old version, and makes it clear we encourage developers to treat not supporting these compiler options as a problem.
> Tweak introduction of compiler options guide

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
`_FORTIFY_SOURCE` won't work without optimization enabled to at least -O1.
I didn't change the `_FORTIFY_SOURCE=2` recommendation to 3; I'll work on that and the fortification section later in the week.
> Add -O2 flag in the TL;DR; example

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
I'd like to propose some edits to the glibcxx_assertions branch that incorporates material on the corresponding flag for LLVM's libc++ standard library and changes the description of the feature to better match the description in GCC and LLVM.
> Precondition checks for C++ standard library calls

- docs/Compiler_Hardening_Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
noexecheap is a Gentoo downstream extension and is not available on any other distributions or in upstream linkers.
> Drop -Wl,-z,noexecheap

- docs/index.md
Add an "index.md" file so that people can view
<https://best.openssf.org> and see all the *released* work from the OpenSSF Best Practices Working Group.
The goal is to make this more discoverable.
We *separately* need to create a "landing page" for developers, one that would cover all OpenSSF work (at least).
That is a *separate* idea, I currently expect that to be developed in `./developer.md`. But let's quickly get this "general list" added, so it'll be easy to find this info!
> Add an index.md to /docs of "released work"

- docs/_config.yml
This modifies `_config.yml` so that the generated pages on <https://best.openssf.org> will have more accurate metadata.
> Improve published metadata

- docs/_config.yml
It turns out that the _config.yml path value
doesn't use a leading "/" when referring to files. Remove it. See:
https://jekyllrb.com/docs/configuration/front-matter-defaults/
This will let us set the descriptions of individual files *without* adding a yml header to the markdown itself. Currently people are jumping directly to the markdown, so we want the markdown as readable as we can make it until people generally use the publishing website best.opennsf.org.
> Omit leading slash in _config.yml path

- docs/_config.yml
The override of the description isn't working.
Modify the _config.yml file so the path uses a glob; this may slow builds slightly, but hopefully it will mean the pattern matches and sets the description.
> In _config.yml use glob in path

- docs/Concise-Guide-for-Developing-More-Secure-Software.md
The title mentions "secure", but the intro sentence doesn't. Add the word "secure" to the intro sentence so that it's clear what the scope of this document is. Adding the word "secure" here seems like the "smallest possible change that does this".
> Add "secure" to the intro text

- README.md
The link to the C/C++ guide is broken after the markdown document was renamed. This PR fixes the link to the markdown file, now labeled "editable version" in the README, and adds a link to the pretty-printed (jekyll generated) version.
> Fixing broken link to C/C++ guide after renaming the document

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Any opinions on the new, proposed wording? The intention is to make it more explicit that the versions indicated should be read as "this version _and newer_".
> Consistently reword 'Supported by' in tables to 'Supported since'

- docs/Compiler-Hardening-Guides/README.md
The readme file in the directory of the hardening guide is mainly empty. This PR adds minimal information about the effort and how to get involved.
> Compiler guide: adding minimal infos to empty readme

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Footnotes only render correctly through jekyll/kramdown when every footnote is surrounded by an empty line and when the identifier is only composed of alphanumeric characters. The linter unfortunately does not check for this.
> Compiler Guide: fix rendering of footnotes

- docs/SCM-BestPractices/README.md
- docs/SCM-BestPractices/github/README.md
- docs/SCM-BestPractices/gitlab/README.md
Following some feedback about the fact that the "Server" section creates confusion - we should change the term to the more general "Enterprise" namespace. That's because the policies under this section don't apply just to servers (GHES / GitLab Self-Managed), They also apply for cloud-based SCMs (e.g. [GitHub Enterprise](https://github.com/enterprise)).
Also in this PR: 
- Additional guide targets
- Putting Legitify as the first suggested tool, as it's the only one that covers all of the guide's policies
> Change "Server" to "Enterprise"

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Fixes incorrect footnote labels and missing code blocks in Compiler Hardening Guide
> Fix compiler guide formatting

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Starting with libc++ release 17.0.0 `-D_LIBCPP_ENABLE_ASSERTIONS` has been deprecated in favor a new hardened mode of operation. Moving `_LIBCPP_ASSERT` to the 'considered options' table and will look into documenting the new hardened mode as a separate set of changes.
- https://libcxx.llvm.org/ReleaseNotes/17.html#deprecations-and-removals
- https://libcxx.llvm.org/Hardening.html
- https://reviews.llvm.org/D154997
Closes issue #149.
> Move -D_LIBCPP_ASSERT to list of considered options

- docs/index.md
As the SCM Guide is officially released, adding it to the main index page.
> Add SCM Guide

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Fixes #164.
Also removes `-Wl,--enable-new-dtags` from list of discouraged options as per @siddhesh's feedback:
> Looking at the _Discouraged Compiler Options_ section a bit closer though, ISTM that the mention of `-Wl,--enable-new-dtags` option is unnecessary. All it does is make the linker generate `DT_RUNPATH` instead of `DT_RPATH` when `-Wl,-rpath` is passed, it doesn't really do anything on its own. Could we just drop it?
Finally, adds an anchor span to the `-Wl,-rpath` description and hyperlink to it from the discouraged options table.
> Fix missing binutils version for rpath

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Fixing some typos and smaller editorial changes discovered while reading through the guide.
> Compiler guide: fixing typos and editorial fixes

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This also documents how to mark *intentional* implicit fallthrough. Developers might be tempted to *not* use this warning if it's not clear how to handle this case.
> Add -Wimplicit-fallthrough

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
In case a compiler uses a predefined default for FORTIFY_SOURCE and a different mode is set on the command line, a warning about redefining the macro is triggered. To avoid this, the default value of FORTIFY_SOURCE can be unset first before setting the desired value.
Fixes #272
> Compiler guide: Add note about redefining default of FORTIFY_SOURCE

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
The current text *way* oversells the value of separate debug info. Depending on separating debug info for security is a terrible idea. Decompilers and similar tools work quite well even when debug info is separate. Also, many of the readers are thinking about open source software, and clearly trying to hide the source code when it's public doesn't make any sense (!).
So I suggest emphasizing the *size* argument (which is uncontroversial), then briefly noting the other argument but emphasizing that hiding debug info doesn't really prevent decompilation.
If you want to hide secrets, omitting debug info is a *terrible* way to do it :-). Let's not claim otherwise.
> Modify rationale for separate debug info

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Buggy applications that use malloc_usable_size to *use* the residual size in the block may crash with _FORTIFY_SOURCE.  Add suggestions to deal with them.
> Add note on _FORTIFY_SOURCE interaction with malloc_usable_size

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Corresponding change as in #297 for the recommended options table
> Add GCC and Clang version to -Wimplicit-fallthrough 

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Fixes #251
This PR implements the version that was identified to be a good compromise in the comments for #251; examples of GCC- and Clang-based compilers are listed in a footnote.
> Refer to more compilers based on GCC and Clang

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Insert headers where they below. For example, the bolded lines should be headers. Once this is done, the front matter is much shorter and simpler, making it easier to navigate.
> Add headers where they belong

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Arg! Somehow the initial dash in `-shared` got dropped in the table reformat. Let's fix that!
> Add missing dash for -shared

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- docs/Compiler-Hardening-Guides/Makefile
Per the CommonMark spec, fenced code blocks should use *3* characters not *4*. Some processors will quietly allow the other, but it can lead to problems, so let's use the standard format.
For more information, see:
<https://spec.commonmark.org/0.30/#fenced-code-blocks>.
> Mend fences - use 3 not 4 characters

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Bump date to 2023-12-06 after changes merged after [C/C++ Compiler Guide BP call 2023-12-06](https://docs.google.com/document/d/1UClGUnOSkOH_wab6Lx43KUdkaK37L8sbWJ_GPZvc1YY/edit#bookmark=id.plsazddai38l).
> Bump date for Compiler Options Hardening Guide for C and C++

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
It's *fine* to use -Werror with selectors that shouldn't ever occur. The problem is -Werror without selectors.
Modify the text to clearly distinguish these two cases.
> More clearly distinguish -Werror with and without selectors

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
These are hinted at, but they should be clearly stated. This will make it much easier to justify the options below (including future options).
> Add threat model, goals, objectives

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Add the following:
* `-fno-delete-null-pointer-checks`
* `-fno-strict-overflow`
* `-fno-strict-aliasing`
* `-ftrivial-auto-var-init`
This is a redo/re-implementation of this pull request, per various comments:
https://github.com/ossf/wg-best-practices-os-developers/pull/139
> Add `-fno-delete-null-pointer-checks` and friends

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
The removed text is only a consideration for the `-Wl,-z,noexecheap` option that has been moved to the list of considered options appendix.
Thanks to @disconnect3d for pointing out the remaining text.
> Remove considerations for JIT in -Wl,-z,noexecstack synopsis

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Add missing GCC and Clang versions for `-fno-strict-overflow`,  `-fno-strict-aliasing`, and `-ftrivial-auto-var-init`
> Add missing supported since versions

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
These options need to be combined due to divergent behavior between GCC and Clang described in #334.
Fixes #334.
> Recommend use of -Wformat and -Wformat=2 together 

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- Correctly attribute implicit int to pointer conversion removal to C89/C90
- Fix incorrect URL to SEI CER C rule INT36-C
Fixes issues brought up in [comment](https://github.com/ossf/wg-best-practices-os-developers/commit/4106fb09ce1a32f118bc774309b646cc62b1256a#r139194996) to #357.
> Correctly attribute implicit int to pointer conversion removal to C89/C90

- docs/labs/input1.html
- docs/labs/input2.html
Put omitted-comma hint at the beginning of the list of hints in labs input1 and input2. It's an easy mistake to make and easier to explain than many other issues. It also serves as a relatively simple pattern to demonstrate how to write hints.
> Labs: Put omitted-comma hint at the beginning

- docs/labs/checker.js
If a button doesn't define a title it doesn't necessarily result in the value being "undefined" or "null" - empty string is possible. I find that odd, but it's reality.
This code changes so that if a button title is falsy at all (null, undefined, or empty string), we set its value. That way every button has a tooltip.
> Fix tooltips for buttons

- docs/labs/checker.js
- docs/labs/create_checker.md
- docs/labs/hello.html
Add a mechanism for testing the preprocessor, document it, and include tests in `hello.html` for the default
preprocessor. That gives us greater confidence that the preprocessor is working correctly.
> Labs: Add mechanism for testing preprocessor

- docs/labs/csp1.html
The display gets cut off at the RHS if it's too wide to start.
> csp1: Start with smaller width

- docs/labs/checker.js
Previously if there were multiple lab entrants, their background color would be set based on cumulative correctness. This was a bug; they should be shown separately.
The only way to notice this is to fill in correct answers in the wrong order, so it's not obvious, but we want to handle this unusual case correctly.
> Show individual statuses as themselves (bugfix)

- docs/labs/checker.js
Add support for Firefox.
The code was using the Set class's "difference" method. This is in Firefox nightly, but is not yet released. So we add a few lines to compute it ourselves. Now it works on Firefox.
> Add Firefox support to labs

- docs/labs/csp1.html
- docs/labs/hello.html
- docs/labs/input1.html
- docs/labs/input2.html
- docs/labs/regex1.html
Modify the lab HTML files to always try to load from best.openssf.org. This is no change for accesses to best.openssf.org, but it means that if you're using the lab locally *and* have internet access, you'll see the same thing. This is an improvement for local testing and individualized use.
Neither approach will allow the use of styles for disconnected operations. That said, the labs will still *work* they'll just look different.
> Change lab html style to refer to best.openssf.org

- docs/labs/README.md
The README has helpful information, but it's really a roadmap and people at first didn't realize that. Modify the tone so it's clearly a roadmap, show stages, and make it clear that these are "planned" not merely "needed".
This commit is per review/comment during an OpenSSF education SIG meeting.
> Tweak tone lab README

- docs/labs/checker.js
- docs/labs/create_checker.md
- docs/labs/oob1.html
One problem with regexes is that by default they aren't able to have named definitions like BNF.
Solve this by implementing "definitions". This only adds a few more lines, but now we have a powerful way to create definitions, while still being fast in execution.
> Implement definitions in checker.js

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Use consistent wording in tl;dr section and heading for detailed description of  options treating obsolete C constructs as errors.
> Use consistent wording for options treating obsolete C constructs as errors

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Adjust description of `fallthrough()` macro to accurately describe guide vs. kernel version after change in #469.
Brought up during discussion in [C/C++ Compiler BP Guide call 2024-05-02](https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit#bookmark=id.90vj0g5nxihp).
> Adjust description of fallthrough macro to accurately describe guide vs. kernel version

- docs/developers.md
Today I learned about sos.dev... and that it probably isn't going to run in 2024. But there are several ongoing programs to fund security improvements in open source software.
I used https://github.com/ossf/wg-securing-software-repos/issues/39 for my data source.
cc @brainwane in case I missed any.
> Update funding options for open source projects.

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
As part of Issue https://github.com/ossf/wg-best-practices-os-developers/issues/490, change compiler and dependency versions to have until patch version.
The goal is to improve machine readability so scripts that extract compiler options from the webpage can easily extract the dependent versions.
For example, `gcc 12` -> `gcc 12.0.0`
Changes done for:
1. gcc
2. clang
3. binutils
4. libstdc++
5. libc++
Changes have only been done in tables, not in any of the paragraph text.
Github shows diff by lines. To see diff by characters (which is easier to read in this case), use - 
`git diff --color-words=.`
> Standardize versions in the "supported since" columns to improve machine readability

- docs/Correctly-Using-Regular-Expressions.md
This converts the Google document into markdown and puts in the docs/ directory. Eventually this should be split into 2 documents, but I think it's easier to do that separately.
> Add Correctly Using Regular Expressions Guide (as 1 page)

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
In the Compiler Hardening Guide, `-D_LIBCPP_ASSERT` is listed as a recommended run-time options (Table 2 of current document), however it is also listed as an option that has been considered but excluded due to it being deprecated (Section 10 of current document.)
This pull request removes `-D_LIBCPP_ASSERT` from the list of recommended run-time options based on our discussion from the previous call.  If/how `-D_LIBCPP_ENABLE_HARDENED_MODE` should be recommended remains an open question.
The copyright date has also been updated.
> Remove -D_LIBCPP_ASSERT from recommended options

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Adds [`-fhardened](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fhardened) introduced in [GCC 14](https://gcc.gnu.org/gcc-14/changes.html) to Compiler Options Hardening Guide.
Fixes #240
> Add -fhardened to Compiler Options Hardening Guide

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- Fix incorrect Clang version given for -fstack-protector-strong.
- Add missing GCC and Clang versions for -fstack-protector and -fstack-protector-all.
- Fixes #512
> Adjust supported since versions for -fstack-protector options

- docs/labs/redos.html
Adding the lab for [Countering ReDoS Attacks on Regular Expressions](https://github.com/ossf/secure-sw-dev-fundamentals/blob/main/secure_software_development_fundamentals.md#countering-redos-attacks-on-regular-expressions).
> Add ReDoS lab

- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-426/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-426/compliant01.bash
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-426/example01.bash
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-426/noncompliant01.bash
- docs/Secure-Coding-Guide-for-Python/readme.md
Moving CWE-426 from confluence as part of #531
Note: existing folder XXX-005 should have been CWE-426 so it has been renamed.
> PyDoc2GitHub CWE-426

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Based on the discussion around #485 in the PR and [Compiler BP Call 2024-06-27](https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit#bookmark=id.dhr32hb9yx35) this PR proposes text to add the `-fvtable-verify ` option to the list of considered options with an indication of the shortcomings identified by @Flo4152, @thesamesam, @jwakely and @siddhesh.
> Add `-fvtable-verify` to list of considered options

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- Clarify RIP-relative addressing is available for certain other instructions other than mov as well
> Refer to 'RIP-relative addressing' in position-independent code description

- docs/labs/shell-injection.html
Somehow the `form` element got dropped, causing the lab to stop working. This fixes it.
> Fix shell-injection lab by adding missing `form`

- docs/labs/input1.html
We mention the required range once, but that may not be obvious enough, so mention it twice.
> input1: Clarify required range

- docs/labs/conversion.html
- docs/labs/csp1.html
- docs/labs/free.html
- docs/labs/handling-errors.html
- docs/labs/input1.html
- docs/labs/input2.html
- docs/labs/oob1.html
- docs/labs/redos.html
- docs/labs/regex0.html
- docs/labs/regex1.html
- docs/labs/shell-injection.html
- docs/labs/sql-injection.html
- docs/labs/template.html
Per discussion in education SIG meeting 2024-09-04, add a note in each lab about the "hint" and "give up" buttons.
> Add notes about the "hint" and "give up" buttons in labs

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> Add -mmitigate-rop to considered compiler options

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- Make section consistent with changes in GCC 14
> Improve description of control-flow protection 

- docs/labs/handling-errors.html
Improve lab handling-errors.html. In particular, add some hints for the last section.
> Improve lab handling-errors.html

- docs/labs/shell-injection.html
An alternative answer is to use "shell=False", so allow it.
My thanks to Helge Wehder for this suggestion.
> shell-injection.html: Allow "shell=False" as an answer.

- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/compliant02.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/example01.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/example02.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/noncompliant02.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Adding documentation to CWE-197 as part of #531
> Adding documentation to CWE-197 as part of #531

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Clarify the description of `-Wtrampolines` and `-Wl,-z,noexecstack` to make it clear code that requires trampolines on the stack will crash with the `-Wl,-z,noexecstack` mitigation and how the usage of `-Wtrampolines` warns of such occurences.
Also adds an additional considerations for -Wl,-z,noexecstack covering:
- how modern compilers determine the noexecstack markings automatically, but missing markings result in the stack being mapped executable
- how Linux versions prior to 5.8 also expose other program data executable if the stack is not mapped as non-executable
> Clarify the interaction between trampolines and `-Wl,-z,noexecstack`

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- Move `-D_FORTIFY_SOURCE` optimization level requirement to the description in the detailed section table
- Reorder `-D_FORTIFY_SOURCE` variants in the detailed section table to be consistent with the ordering of other options
- Add additional information to "additional considerations" on how optimization levels affect `-D_FORTIFY_SOURCE` performance
> Clarify `-D_FORTIFY_SOURCE` interaction with optimization levels

- docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-390/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-390/compliant02.py
- docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-390/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-390/noncompliant02.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Moving CWE-390 code example to GitHub as part of #531
> Moving CWE-390 code example to GitHub as part of #531

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This PR adds an "additional considerations" section for the `-Wl,-z,relro` and `-Wl,-z,now` options section noting that shared libraries built without RELRO will prevent the application from benefitting from these hardening flags.
> Add note on enabling RELRO for library dependencies

- docs/labs/README.md
These tier-1 labs had been assigned, but I haven't heard from the assignees for over a month, even after repeated requests. So I'm unassigning these specific labs.
I presume that other tasks have (unfortunately) had to take priority. That happens. It's possible they had a more serious problem, e.g., a medical issue; if so, we hope they're okay!
I hope they'll be able to rejoin this effort at some future time.
> Unassign labs for hardcoded credentials and XSS

- docs/labs/README.md
- docs/labs/xss.html
This adds a lab to practice countering
cross-site scripting (XSS) vulnerabilities.
I decided to use Python, Flask, and Jinja2,
as they're common and easy to exaplain.
Also, Jinja2 and Flask have a quirk - Jinja2 doesn't escape by default, but when brought in via Flask,
Flask enables it. That gives us an easy excuse to
discuss how to configure templating systems as necessary.
I ended up making this a multi-part lab.
That seemed like the best way to illustrate some important concepts when talking about how to escape values at scale.
> Add lab xss.html

- docs/labs/format-strings.html
Uses the python string format to demonstrate the [Format Strings and Templates ](https://github.com/ossf/secure-sw-dev-fundamentals/blob/main/secure_software_development_fundamentals.md#format-strings-and-templates) section of course.
This example came from [Be Careful with Python's New-Style String Format](https://lucumr.pocoo.org/2016/12/29/careful-with-str-format/) by Armin Ronacher and was produced in collaboration with @david-a-wheeler
> add sending output format strings lab with python string format

- docs/labs/insecure-deserialization.html
Adding the lab for [Insecure Deserialization](https://github.com/ossf/secure-sw-dev-fundamentals/blob/main/secure_software_development_fundamentals.md#insecure-deserialization)
> Add insecure deserialization lab

- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-681/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-617/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-617/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-617/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Adding documentation to CWE-617 as part of #531
> Adding documentation to CWE-617 as part of #531

- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/01/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/01/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/01/example01.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/01/example02.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-197/01/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Signed-off-by: Helge Wehder <helge.wehder@ericsson.com>
part of #531
> pyDoc2GitHub Adding documentation for CWE-197 01 as part of #531 to GitHub

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> Discourage use of sanitizers for SUID binaries

- docs/labs/format-strings.html
- docs/labs/src/format-strings.py
Add "hints:" (without the field name, it has no contents).
Remove an example of a password in source code.
That is a vulnerability all by itself, we do NOT want to show how to write *vulnerable* code.
> Fix lab format-strings

- docs/labs/checker.js
- docs/labs/create_checker.md
- docs/labs/deserialization.html
- docs/labs/handling-errors.html
- docs/labs/mass-test
- docs/labs/regex1.html
Improve how labs are tested.
Change how the "examples" are used in the hint section so that people provide full examples up to the tested index, and *document* this (before it wasn't clear how do this). By using this approach we will *consistently* test hints.
In the longer term, we might remove the constraint on which hints are returned during the testing, but that requires determining which forms cover which indexes, which is more complex. By asking for the fields now, we make it easier to make that change later.
This makes changes in labs to *use* the new testing mechanism in hint examples.
This also adds the script "mass-test", which automatically tests all labs. It does this by opening them all in the web browser, triggering the self-test in each lab. You have to manually look at …
> Improve lab testing

- docs/SCM-BestPractices/README.md
Add link to additional source code platform management configuration guidance focused on collaboration by InnerSource Commons (non-profit) 
This was previously discussed in working group video call and https://github.com/ossf/wg-best-practices-os-developers/issues/557
> Add link to additional source code platform management configuration guidance focused on collaboration

- docs/Secure-Coding-Guide-for-Python/contribution/README_TEMPLATE.md
The change aims to create a simple template for creating README files for Secure Coding Python Guides. By using the template, we can ensure that all of the rule descriptions follow the same format in regard to page sections, code examples, bibliography, etc. The template also contains the link to quoting reference guide we have decided to follow.
The template should be mentioned on the landing page referenced in #520
> pySCG: template for contributing to the project

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
To deal with old gcc versions that do not have `__has_attribute`, the gcc manual suggest using this form. 
See https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005fattribute.html
> Fix fallthrough example macro to work with very old gcc versions

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> Retire CLANG_DEFAULT_PIE_ON_LINUX in favor of Clang configuration files

- .gitignore
This improves the experience when previewing the generated site using a local Jekyll instance
> Add Jekyll-generated site, metadata, and cache to gitignore

- docs/Secure-Coding-Guide-for-Python/readme.md
pySCG main readme table was missing the CVEs for 755 and 532 as part of #531 , added now.
> pySCG adding missing CVEs for 755 and 532

- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/noncompliant02.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Adding CWE-78 as part of #531 
also building on top of discussion from #654
> pySCG adding CWE-78 code and doc

- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
- docs/Secure-Coding-Guide-for-Python/readme.md
Adding [CVE-2024-43804](https://nvd.nist.gov/vuln/detail/CVE-2024-43804)  into main readme table for CWE-78
> pySCG: adding prominent CVE for CWE-78 to main readme

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
During the [C/C++ Compiler CP Call 2024-10-31](https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit?tab=t.0#bookmark=id.u0decq6dhlw4) @david-a-wheeler noted during the discussion regarding #681 that it would be good to state the relevant compiler versions for the `__fallthrough__` attribute and feature testing via `__has_attribute. This PR adds a note on the necessary compiler versions below the example fallthrough macro definition.
> Clarify compiler versions for `__fallthrough__` attribute and feature testing via `__has_attribute`.

- docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-489/README.md
- docs/Secure-Coding-Guide-for-Python/readme.md
Adding documentation to CWE-489 as part of #531
> pySCG: Adding documentation to CWE-489

- docs/labs/checker.js
Modify the stamp so that if the user gave up before solving the lab, the stamp is subtly marked to indicate that.
> Indicate if user gave up first inside stamp

- docs/assets/css/style.scss
Switch to OpenSSF brand colors for hyperlink text. The OpenSSF Brand Guidelines are here:
https://openssf.org/about/brand-guidelines/
We changed best.openssf.org to use OpenSSF's fonts long ago, but we never changed the hyperlink colors to adhere to the guidelines. This commit changes hyperlinks to also use OpenSSF brand colors.
I intentionally chose dark colors to provide *strong* contrast with the white background.  This site provides mostly documents, with with text that is smaller than the main OpenSSF website. So ensuring we have *good* contrast between the text and the background seemed especially important.
For more about changing link colors, see:
https://www.w3schools.com/css/css_link.asp
I suggest that we can argue about changing these colors later. Once this commit is accepted, …
> Use OpenSSF brand colors, fixes #160

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Clarify compiler options hardening limitations when linking to pre-built artifacts
Fixes #705
> Clarify compiler options hardening limitations when linking to pre-built artifacts 

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Improve `-fno-strict-overflow` description and document changes in GCC 8.5.
Add `-ftrapv` and `-fsanitize=signed-integer-overflow` as alternative options.
Add missing "When not to use?", "Performance implications", and "Other considerations subsections" 
Fixes https://github.com/ossf/wg-best-practices-os-developers/issues/685
> Improve -fno-strict-overflow description

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> Add `-fsplit-stack` to considered compiler options

- docs/labs/checker.js
To encourage people to *try* to do the labs, if they pick "give up" too soon after loading, we'll instead tell them to try harder first. It also shows the number of seconds elapsed (a strong hint that this is timed).
This intentionally does not show the minimum time. The purpose is to get people to work on the lab, not to encourage them to game the timer.
> Labs: Make "give up" require a certain number of seconds

- docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-392/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-392/compliant03.py
The code snippet incorrectly returns `res` when it should be returning `ret`. This doesn't really have an effect, since the sample demonstrates failing early.
> Fix typo in return value from README (fixes #652)

- docs/labs/checker.js
- docs/labs/create_checker.md
- docs/labs/hello.html
- docs/labs/hello.js
Currently configuration is mostly in a YAML file embedded in the lab's HTML. This means that the lab configuration cannot be shared between locales (translations), which is annoying.
We can't easily load YAML or JSON from a separate file when running or testing locally. However, we *can* easily load a separate file if it's in JavaScript format.
This switches the configuration of lab hello.html so it uses the configuration in hello.js.
> Create/implement separate hello.js for hello.html config

- docs/labs/checker.js
Fix the congrats message - if there's more than one, show the one for "all" (it was unintentionally the other way around).
> Lab nit: Show correct "you're correct" message

- docs/labs/checker.js
- docs/labs/ja_hello.html
This adds lab `ja_hello.html`, a Japanese translation of lab `hello.html`. It also adds various fixes of `checker.js`, because the process of implementing this lab revealed some bugs in our library.
> Add lab ja_hello.html: Demo Japanese translation

- docs/labs/assert.js
- docs/labs/input1.js
- docs/labs/regex0.js
- docs/labs/regex1.js
JSON requires double-quotes in places that JavaScript does not. Since it's in JavaScript, use the simpler format.
> Simplify .js files - remove unnecessary double-quotes

- docs/labs/redos.html
- docs/labs/redos.js
We're removing the YAML and moving the answers to a shared JavaScript so that we can easily internationalize (and remove a library we don't really need). I believe this is the last one.
> Lab redos: Move answers to shared JavaScript

- docs/labs/checker.js
When Chrome is presented with a natural language, it can offer to translate the HTML page. Unfortunately, this caused labs to fail.
This commit modifies to code to work around this, so that after translation the lab continues to work.
The explanation about the lab is translated.
Unfortunately, this does *not* translate the responses shown via alert boxes (e.g., hints and congrats).
However, since the lab now *works*, users can copy that text into something to do a translation.
This commit makes the labs much more accessible to those who speak natural languages we don't currently have translations for.
> Handle in-browser translations more gracefully

- docs/labs/argument-injection.html
- docs/labs/assert.html
- docs/labs/checker.js
- docs/labs/conversion.html
- docs/labs/csp1.html
- docs/labs/deserialization.html
- docs/labs/format-strings.html
- docs/labs/free.html
- docs/labs/handling-errors.html
- docs/labs/hardcoded.html
- docs/labs/hello.html
- docs/labs/input1.html
- docs/labs/input2.html
- docs/labs/ja_hello.html
- docs/labs/oob1.html
- docs/labs/redos.html
- docs/labs/regex0.html
- docs/labs/regex1.html
- docs/labs/shell-injection.html
- docs/labs/sql-injection.html
- docs/labs/template.html
- docs/labs/xss.html
We've switched from using YAML to using JavaScript directly for storing data. One reason to do that was simply that it's the only easy way to load data when running locally.
A second reason, however, is that this means we can completely eliminate the use of this library at run-time. Not using a library at *all* eliminates the need to maintain it, update it, etc. It also speeds loading; nothing loads faster than code you don't load at all :-).
> Remove YAML processing library

- docs/labs/README.md
- docs/labs/checker.js
- docs/labs/fr_hello.html
- docs/labs/hello.js
This is merely a machine language translation, so I'm sure it's imperfect. However, it's useful for testing our internationalization support. For example, Firefox has built-in translation support for French but not yet for Japanese, and this is a useful sample for testing it. I can also read some French, so I can more confidently test it.
> Create lab fr_hello.html (French translation)

- docs/labs/create_checker.md
When we dropped YAML, this documentation became
obsolete. Fix it to match our changes to the labs
for internationalization.
> Fix preprocessor documentation

- docs/labs/argument-injection.js
- docs/labs/assert.js
- docs/labs/checker.js
- docs/labs/conversion.js
- docs/labs/csp1.js
- docs/labs/deserialization.js
- docs/labs/format-strings.js
- docs/labs/free.js
- docs/labs/handling-errors.js
- docs/labs/hardcoded.js
- docs/labs/hello.js
- docs/labs/input1.js
- docs/labs/input2.js
- docs/labs/oob1.js
- docs/labs/redos.js
- docs/labs/regex0.js
- docs/labs/regex1.js
- docs/labs/shell-injection.js
- docs/labs/sql-injection.js
- docs/labs/template.js
- docs/labs/xss.js
Make the license clearer per file.
> Add copyright and license statements to each .js file

- docs/labs/argument-injection.js
- docs/labs/assert.js
- docs/labs/conversion.js
- docs/labs/csp1.js
- docs/labs/deserialization.js
- docs/labs/format-strings.js
- docs/labs/free.js
- docs/labs/handling-errors.js
- docs/labs/hardcoded.js
- docs/labs/redos.js
- docs/labs/shell-injection.js
- docs/labs/sql-injection.js
A common error when modifying the JavaScript files is forgetting to add a separating comma to the previous line. This is detected when loading (including any tests), but it's still annoying. To reduce the likelihood of this error, add trailing commas to lines of the form "..."
> Add trailing commas to text lines

- docs/labs/checker.js
Add delay for a hint. That way, instead of trying to use hints to write the answers, learners will be quietly encouraged to try to solve the problem themselves.
This adds a shorter delay (15 seconds) for each hint. If the user has seen a hint and hasn't changed anything, they can re-see the hint.
We earlier added a delay for "give up". This modifies the give up timer so that if they've asked for a hint, the give up timer starts from the time of the last hint. That way, people *can* give up, but they have to at least wait a little time.
> Add delay for a hint

- docs/labs/checker.js
While JavaScript *allows* global properties on Strings to be added, it's not necessarily a good idea, as those are global (and could interfere with other things).
To reduce the risk of future problems, use a created function instead, to avoid conflicts.
This also adds a myAssert and improves internal comments about indexing as related changes.
> Refactor format() so it's not a global String property

- docs/Secure-Coding-Guide-for-Python/readme.md
As per SIG meeting Dec 16, addressing our unclear scope in our introduction of the main readme.md.
Removed some duplicated and long winded wording.
Fixed links and references.
Fixed formatting issues.
> pySCG: updated to scope addressing Davids feedback, fixed formatting

- docs/labs/hello.js
- docs/labs/ja_hello.html
**Description**
・Fix Japanese translations in hello.html and hello.js to sound more naturally
> Translate "Lab Exercise hello" into Japanese

- docs/Secure-Coding-Guide-for-Python/readme.md
fixing accidentally introduced linter errors
> Python Guide: fixing accidentally introduced linter errors

- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-681/01/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-681/01/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-681/01/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Created a page for sub-directory of CWE-681:
CWE-681: Avoid an uncontrolled loss of precision when passing floating-point literals to a Decimal constructor
> CWE-681- 01 - README and code examples added

- docs/Secure-Coding-Guide-for-Python/readme.md
The "NOTE" marking doesn't work in our rendering pipeline, so let's fix the formatting.
> Fix formatting of note that Python guide is a draft

- docs/labs/input2.html
This PR fixes some typos, specifically the paths, in labs/input2.html (which were found during the translation)
> Fix typos in labs/input2.html

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Reorganize the front part of the
"Compiler Options Hardening Guide for C and C++"
for clarity.
There is a recent and very interesting post
"Mitigating a rsync Vulnerability: A Lesson in Compiler Hardening" by Mark Esler on March 19, 2025 at
<https://www.chainguard.dev/unchained/mitigating-a-rsync-vulnerability-a-lesson-in-compiler-hardening>
However, that post says "Chainguard implements most recommendations, and takes them a step further by also opting into..." and then adds options that our guidance *specifically* recommends. E.g., it adds `-fPIE` and `-PIC`, `-fsf-protection=full`, and so on.
This shows that even smart people who *read* the guidance think that only the list at the top is relevant, and don't even look at the table below it.
Let's put the table *immediately* after it, …
> Reorg front of Compiler Options Hardening Guide for clarity

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
It turns out there's a survey of C/C++ hardening flags. Let's cite it!
> Add citation of survey of C/C++ hardening flags

- docs/spp/Simplest-Possible-Process.md
Now that others are looking at applying the SPP,
it's clear we need to clean up its documentation.
This PR tries to do that. This has no technical changes, it's purely wording changes to make it easier to understand.
> Clean up SPP documentation

- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-362/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-362/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-362/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/readme.md
pySCG: Adding documentation to CWE-362 as part of #531
> pySCG: Adding documentation to CWE-362 as part of #531

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Make assumptions clearer about the impact of the target platform and how it influences compiler output.
cc @voltur01
> Add clarifications on AArch64 PAC and BTI

- docs/index.md
This PR adds the Memory Safety Continuum document to the best.openssf.org website.
> Release of The Memory Safety Continuum

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
This fixes a few small issues in the "Compiler Options Hardening Guide for C and C++" guide.
> Typo and misc fixes

- docs/Secure-Coding-Guide-for-Python/CONTRIBUTING.md
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-134/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-681/01/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-1335/01/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
- docs/Secure-Coding-Guide-for-Python/readme.md
- docs/Secure-Coding-Guide-for-Python/templates/README_TEMPLATE.md
- docs/Secure-Coding-Guide-for-Python/templates/compliant01.py
- docs/Secure-Coding-Guide-for-Python/templates/example01.py
- docs/Secure-Coding-Guide-for-Python/templates/noncompliant01.py
> Fixes issue #839

- docs/labs/input2.js
- docs/labs/ja_input2.html
This patch translates input2 in Labs into Japanese.
Please review the translation first @ninan27 @Muuhh-CTJ
> ja_input2.html: Translate labs/input2 into Japanese

- docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
This restructure suggestion PR does the following:
The most important:
* Restructures the information (and does not remove any information from the original document) into simple tables with a theme header, and rules-description format. Aims to make the structure for the user clearer, and hit a add sweet spot between between, let's say a formal ISO 270x doc and something aimed at a developer/tech doing assessment.
* In the same mood, tightens up the language making it a bit more imperative, Verify that, Do that, ex.!
Other:
* Adds basic terminology list
* Adds a version table
* Adds a checkbox to that tables, (This is just an idea, and I don't know if I even like it myself, maybe not... let me know). Intended to use as a check-list, for the end user. Stay in, remove it?
This suggestion …
> docs: restructure concise evaluating guide,  add terminology list

- docs/index.md
This commit adds a missing hyperlink.
We previously created the guide
"Correctly Using Regular Expressions for Secure Input Validation" at <https://best.openssf.org/Correctly-Using-Regular-Expressions> and list this guide at <https://openssf.org/resources/guides/>. We forgot to add the guide to the list at best.openssf.org.
This commit adds a link to the guide from
<https://best.openssf.org/>, where it should have been added as well.
> Add "Correctly Using RE" to best.openssf.org index

- docs/assets/css/style.scss
Boldly go where no one has gone before.
In default body text (Cairo font) it's hard to tell which text is bold and which not.
This increases the font weight, hopefully making bold and strong text easier to identify.
> Embolden website text

- docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
Splitting the evaluation criterion about inappropriate suitability of a project into two seperate ones to make each one more clear:
- widely adopted projects have a higher change of being maintained,
- a user shall select a technology that solves the concrete problem at hand and not because it is the latest tech
Fixes #853
> Concise Evaluation Guide: Split recommendation in two separate ones

- docs/Secure-Coding-Guide-for-Python/readme.md
CVE info was missing on main pySCG readme, added.
> pySCG 180 adding cv einfo

- docs/labs/handling-errors.js
- docs/labs/ja_handling-errors.html
This patch adds Japanese translation for handling-errors in Labs.
Please review the translation first @ninan27 @Muuhh-CTJ
> ja_handling-errors.html: Translate labs/handling-errors into Japanese

- docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/compliant02.py
- docs/Secure-Coding-Guide-for-Python/CWE-682/CWE-191/noncompliant02.py
Trying to address issues reported in #835 , the excessive attack section might be to much but covers all boundaries I discovered.
> pySCG bugfix for CWE-191 as per #835

- docs/labs/README.md
Japanese translation for labs listed as "available" on docs/labs/README.md has been completed.  This PR adds links to them on docs/labs/README.md.
This is related to Japanese translation but not including Japanese.
So it is not eligible for "Japanese" label...IMHO.
> Add links to Japanese labs on README.md

- docs/labs/format-strings.js
The conditons should be intended as "user_format", instead of "user_input".
> Fix hint conditions of format-strings.js

- docs/labs/conversion.html
Issue : Sample code didn't call get_queue() and queue_count was not set.
Fix : Added the calling of get_queue() to set its return value for queue_count.
Trivial fix but a sample code should be consistent, I think.
> Fix the sample code in conversion.html

- docs/labs/conversion.js
- docs/labs/ja_conversion.html
Japanese translaton for docs/labs/conversion.html and conversion.js
I would like @ninan27 @shimos to review Japanese translation part first.
This is Japanese translation PR, so I would like a mainter to label "Japanese".
> Japanese translation of conversion

- docs/labs/deserialization.js
- docs/labs/ja_deserialization.html
This patch adds Japanese translation for labs/deserialization.
Please review the translation first @Muuhh-CTJ @ninan27
> Add Japanese translation for labs/ja_deserialization

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
The -fcf-protection argument check is not currently supported by [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html).
Fixes #901.
> Fix the incorrect Clang version for -fcf-protection=check

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Add missing synopsis subheadings to compiler options descriptions without them.
> Add missing synopsis subheadings

- docs/Compiler-Hardening-Guides/Compiler-Annotations-for-C-and-C++.md
The `access` attribute allows annotating access restrictions for positional argument to improve the diagnostics output by the `-Wstringop-overread`, `-Wstringop-overflow`, `-Wuninitialized`, `-Wmaybe-uninitialized`, and `-Wunused` warnings.
> Add detailed description of GCC access attributes to Compiler Annotations Guide

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
Fixes #326 together with #931.
> Add -fsanitize-minimal-runtime and -fsanitize-trap=undefined to UBSan description table

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
UBSan can be used in production environment if special minimal runtime is used.
> Add info on minimal UBSan runtime

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
- Give correct GCC version for `-Werror=incompatible-pointer-types` and `-Werror=int-conversion`
Fixes #924
> Clarify obsolete C construct warnings are valid for C code only

- docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-710/CWE-1095/noncompliant01.py
Before this commit the wording was that modifying list works but is not recommended.
But it works as long as no two consecutive elements are deleted, otherwise part of elements is not checked at all without any exceptions raised.
Changed README.md, compliant01.py and noncompliant01.py to demonstrate that.
> CWE-1095: show that list modification is dangerous

- docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> Clarify that ASan can be used with LeakSan

- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-783/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-783/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-783/example01.py
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-783/example02.py
- docs/Secure-Coding-Guide-for-Python/CWE-691/CWE-783/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/readme.md
> pySCG: adding 783 as part of #531

- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-117/README.md
- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-117/compliant01.py
- docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-117/noncompliant01.py
- docs/Secure-Coding-Guide-for-Python/readme.md
Documentation and code samples for CWE-117 (Improper Output Neutralization for Logs) in the Python Secure Coding Guide.
> pySCG: adding 117 as part of #531
